# Builder
FROM quay.io/dougrabson/freebsd14.1-base:latest AS builder

RUN pkg install -y zig

WORKDIR /app
COPY build.zig .
COPY build.zig.zon .
COPY src ./src
RUN zig build -Doptimize=ReleaseSmall
RUN ls -l zig-out/bin

# Runner
FROM quay.io/dougrabson/freebsd14.1-minimal:latest
WORKDIR /app
COPY --from=builder /app/zig-out/bin/hello-freebsd .

CMD ["/app/hello-freebsd"]
